apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-fastapi-prod-sa
  namespace: gke-fastapi-prod
  annotations:
    iam.gke.io/gcp-service-account: gke-fastapi-prod-gsa@YOUR_PROJECT_ID.iam.gserviceaccount.com
